import re
from playwright.sync_api import Playwright, sync_playwright, expect


def run(playwright: Playwright) -> None:
    browser = playwright.chromium.launch(headless=False)
    context = browser.new_context()
    page = context.new_page()
    page.goto("https://erp.91miaoshou.com/?redirect=%2Fpddkj%2Fcollect_box%2Fitems")
    page.get_by_role("textbox", name="手机号/子账号/邮箱").click()
    page.get_by_role("textbox", name="手机号/子账号/邮箱").fill("lyl12345678")
    page.get_by_role("textbox", name="密码").click()
    page.get_by_role("textbox", name="密码").fill("Lyl12345678.")
    page.get_by_role("button", name="立即登录").click()
    page.get_by_role("dialog").filter(has_text="【线上直播】11月05日—11月06日线上直播预告2025").get_by_label("关闭此对话框").click()
    page.get_by_role("button", name="关闭此对话框").click()
    page.get_by_role("link", name="公用采集箱").click()
    page.get_by_role("button", name="我知道了").click()
    page.get_by_text("全部 (7687)").click()
    page.get_by_role("menuitem", name="Temu全托管").click()
    page.get_by_text("全部 (81471)").click()
    page.locator(".jx-checkbox").first.click()
    page.locator("div").filter(has_text=re.compile(r"^标题$")).click()
    page.get_by_role("button", name="预览").click()
    page.get_by_role("button", name="保存修改").click()
    page.get_by_role("button", name="关闭", exact=True).click()
    page.get_by_text("英语标题").click()
    page.locator("div").filter(has_text=re.compile(r"^使用新英语标题:Abc$")).get_by_role("textbox").click()
    page.locator("div").filter(has_text=re.compile(r"^使用新英语标题:Abc$")).get_by_role("textbox").fill(" ")
    page.get_by_role("button", name="预览").click()
    page.get_by_role("button", name="保存修改").click()
    page.get_by_role("button", name="关闭", exact=True).click()
    page.get_by_text("类目属性").click()
    page.get_by_role("textbox", name="请选择类目").click()
    page.get_by_role("textbox", name="请选择类目").click()
    page.get_by_role("textbox", name="请选择类目").fill("家具")
    page.get_by_role("textbox", name="请选择类目").press("Shift+Enter")
    page1 = context.new_page()
    page1.goto("https://erp.91miaoshou.com/pddkj/collect_box/items?")
    page1.goto("https://erp.91miaoshou.com/pddkj/collect_box/items")
    page.get_by_role("textbox", name="请选择类目").click()
    page.get_by_role("textbox", name="请选择类目").click()
    page.locator(".el-loading-spinner").click()
    page.get_by_role("menuitem", name="收纳用品 ").locator("span").first.click()
    page.get_by_role("menuitem", name="收纳篮、箱子、盒子 ").locator("span").first.click()
    page.get_by_role("menuitem", name="盖式储物箱").locator("span").first.click()
    page.get_by_role("button", name="预览").click()
    page.locator("form").filter(has_text="方式一:使用新类目： 产品推荐用途 用于酒杯 用于圣诞饰品 用于工艺品 用于化妆品和化妆品 用于交易卡 多用途 形状 矩形 圆形 椭圆形 五角形 心形 六角形 ").get_by_placeholder("请选择", exact=True).first.click()
    page.locator(".vue-recycle-scroller__item-view.hover > div > .jx-pro-virtual-table__row > div:nth-child(3) > .jx-pro-link").click()
    page.locator("form").filter(has_text="方式一:使用新类目： 产品推荐用途 形状 矩形 圆形 椭圆形 五角形 心形 六角形 三角形 正方形 八角形 其他形状 材料 玻璃 竹 金属 塑料 藤 木材 织物").get_by_placeholder("请选择", exact=True).first.click()
    page.get_by_role("listitem").filter(has_text="多用途").click()
    page.locator("form").filter(has_text="方式一:使用新类目： 产品推荐用途 形状 矩形 圆形 椭圆形 五角形 心形 六角形 三角形 正方形 八角形 其他形状 材料 玻璃 竹 金属 塑料 藤 木材 织物").get_by_placeholder("请选择", exact=True).nth(1).click()
    page.locator(".vue-recycle-scroller__item-view.hover > div > .jx-pro-virtual-table__row > div:nth-child(3) > .jx-pro-link").click()
    page.locator("form").filter(has_text="方式一:使用新类目： 产品推荐用途 形状 材料 玻璃 竹 金属 塑料 藤 木材 织物 聚氨酯 陶瓷 铝 黄铜 铸铁 铜 白镴 银 不锈钢 锡 树脂 桦木 雪松 ").get_by_placeholder("请选择", exact=True).nth(1).click()
    page.get_by_role("listitem").filter(has_text="其他形状").click()
    page.locator("form").filter(has_text="方式一:使用新类目： 产品推荐用途 形状 材料 玻璃 竹 金属 塑料 藤 木材 织物 聚氨酯 陶瓷 铝 黄铜 铸铁 铜 白镴 银 不锈钢 锡 树脂 桦木 雪松 ").get_by_placeholder("请选择", exact=True).nth(2).click()
    page.get_by_role("listitem").filter(has_text="其他材料").click()
    page.locator("form").filter(has_text="方式一:使用新类目： 产品推荐用途 形状 材料 闭合类型 夹上 闩锁 鸥翼 翻盖 磁性 其他闭合类型 风格 复古 波西米亚 华丽 经典 当代 传统 国际 科德角").get_by_placeholder("请选择", exact=True).nth(3).click()
    page.get_by_role("listitem").filter(has_text="其他闭合类型").click()
    page.locator("div:nth-child(5) > div > .category-attr-item-value > .el-form-item > .el-form-item__content > .category-attr-item-value-content > .el-select > .el-input > .el-input__suffix > .el-input__suffix-inner > .el-select__caret").click()
    page.get_by_role("listitem").filter(has_text="当代").click()
    page.get_by_role("button", name="预览").click()
    page.get_by_role("button", name="保存修改").click()
    page.get_by_role("button", name="关闭", exact=True).click()
    page.get_by_role("dialog").get_by_text("主货号").click()
    page.get_by_role("button", name="预览").click()
    page.get_by_role("button", name="保存修改").click()
    page.get_by_role("button", name="关闭", exact=True).click()
    page.get_by_text("外包装").click()
    page.get_by_role("dialog").locator("form div").filter(has_text="外包装形状: 不规则 长方体 圆柱体").get_by_placeholder("请选择").click()
    page.get_by_text("长方体", exact=True).click()
    page.get_by_role("dialog").locator("form div").filter(has_text="外包装类型: 硬包装 软包装+硬物 软包装+软物").get_by_placeholder("请选择").click()
    page.get_by_text("硬包装", exact=True).click()
    page.get_by_role("radio").filter(has_text="addImages").click()
    page.get_by_role("dialog").locator("span").filter(has_text="本地上传 选择空间图片 使用网络图片").click()
    page.locator("#el-popover-4055").get_by_text("选择空间图片").click()
    page.locator("div").filter(has_text=re.compile(r"^微信图片_20250922105854_7_5\.jpg1702 x 1276230\.47 KB$")).get_by_role("img").click()
    page.get_by_role("button", name="确定").click()
    page.get_by_role("button", name="预览").click()
    page.get_by_role("button", name="保存修改").click()
    page.get_by_role("button", name="关闭", exact=True).click()
    page.get_by_text("产地").click()
    page.get_by_role("dialog", name="dialog").get_by_placeholder("请选择或输入搜索").click()
    page.get_by_role("dialog", name="dialog").get_by_placeholder("请选择或输入搜索").fill("浙江")
    page.get_by_text("中国大陆 / 浙江省").click()
    page.get_by_role("button", name="保存修改").click()
    page.get_by_role("button", name="关闭", exact=True).click()
    page.get_by_role("button", name="预览").click()
    page.get_by_role("button", name="保存修改").click()
    page.get_by_role("button", name="关闭", exact=True).click()
    page.get_by_text("定制品").click()
    page.get_by_role("button", name="预览").click()
    page.get_by_role("button", name="保存修改").click()
    page.get_by_role("button", name="关闭", exact=True).click()
    page.get_by_text("敏感属性").click()
    page.get_by_role("button", name="预览").click()
    page.get_by_role("button", name="保存修改").click()
    page.get_by_role("button", name="关闭", exact=True).click()
    page.get_by_text("重量").click()
    page.get_by_role("spinbutton").nth(2).click()
    page.get_by_role("spinbutton").nth(2).press("ArrowRight")
    page.get_by_role("spinbutton").nth(2).press("ArrowRight")
    page.get_by_role("spinbutton").nth(2).press("ArrowLeft")
    page.get_by_role("spinbutton").nth(2).press("ArrowLeft")
    page.get_by_role("spinbutton").nth(2).press("ArrowLeft")
    page.get_by_role("spinbutton").nth(2).fill("6000.00")
    page.get_by_role("button", name="预览").click()
    page.get_by_role("button", name="保存修改").click()
    page.get_by_role("button", name="关闭", exact=True).click()
    page.get_by_text("尺寸").click()
    page.locator("div").filter(has_text=re.compile(r"^长:CM$")).get_by_role("spinbutton").click()
    page.locator("div").filter(has_text=re.compile(r"^长:CM$")).get_by_role("spinbutton").fill("7500")
    page.locator("div").filter(has_text=re.compile(r"^长:CM$")).get_by_role("spinbutton").press("ArrowRight")
    page.locator("div").filter(has_text=re.compile(r"^长:CM$")).get_by_role("spinbutton").press("ArrowRight")
    page.locator("div").filter(has_text=re.compile(r"^长:CM$")).get_by_role("spinbutton").fill("75")
    page.locator("div").filter(has_text=re.compile(r"^宽:CM$")).get_by_role("spinbutton").click()
    page.locator("div").filter(has_text=re.compile(r"^宽:CM$")).get_by_role("spinbutton").press("ControlOrMeta+a")
    page.locator("div").filter(has_text=re.compile(r"^宽:CM$")).get_by_role("spinbutton").fill("71")
    page.locator("div").filter(has_text=re.compile(r"^高:CM$")).get_by_role("spinbutton").click()
    page.locator("div").filter(has_text=re.compile(r"^高:CM$")).get_by_role("spinbutton").press("ControlOrMeta+a")
    page.locator("div").filter(has_text=re.compile(r"^高:CM$")).get_by_role("spinbutton").fill("65")
    page.get_by_role("button", name="预览").click()
    page.get_by_role("button", name="保存修改").click()
    page.get_by_role("button", name="关闭", exact=True).click()
    page.get_by_role("dialog").get_by_text("平台SKU").click()
    page.locator(".el-checkbox.jx-pro-checkbox > .el-checkbox__input > .el-checkbox__inner").first.click()
    page.get_by_role("button", name="预览").click()
    page.get_by_role("button", name="保存修改").click()
    page.get_by_role("button", name="关闭", exact=True).click()
    page.get_by_text("SKU分类").click()
    page.get_by_role("textbox", name="分类").click()
    page.get_by_text("组合装").click()
    page.get_by_role("textbox", name="数量").first.click()
    page.get_by_role("textbox", name="数量").first.fill("500")
    page.locator("div:nth-child(2) > .el-input > .el-input__suffix > .el-input__suffix-inner > .el-select__caret").click()
    page.get_by_text("不是独立包装").click()
    page.get_by_role("button", name="预览").click()
    page.get_by_role("button", name="保存修改").click()
    page.get_by_role("button", name="关闭", exact=True).click()
    page.get_by_text("尺码表").click()
    page.get_by_text("建议售价").click()
    page.get_by_role("radio", name="使用公式:").click()
    page.get_by_role("textbox", name="倍数").click()
    page.get_by_role("textbox", name="倍数").fill("10")
    page.get_by_text("使用公式: 币种： CNY（¥） CNY（¥） USD").click()
    page.get_by_role("button", name="预览").click()
    page.get_by_role("button", name="预览").click()
    page.get_by_role("button", name="保存修改").click()
    page.get_by_role("button", name="关闭", exact=True).click()
    page.get_by_text("包装清单").click()
    page.get_by_role("button", name="预览").click()
    page.get_by_role("button", name="保存修改").click()
    page.get_by_role("button", name="关闭", exact=True).click()
    page.get_by_text("轮播图").click()
    page.get_by_text("颜色图").click()
    page.get_by_text("产品说明书").click()
    page.get_by_role("button", name="上传文件").click()
    page.get_by_role("button", name="上传文件").click()
    page.get_by_role("tooltip", name="本地上传").locator("div").first.click()
    page.locator("#el-popover-5067").get_by_text("本地上传").set_input_files("超多小语种版说明书(1).pdf")
    page.get_by_role("button", name="预览").click()
    page.get_by_role("button", name="保存修改").click()
    page.get_by_role("button", name="关闭", exact=True).click()
    page.locator(".edit-box-header-side > .el-icon-close").click()

    # ---------------------
    context.close()
    browser.close()


with sync_playwright() as playwright:
    run(playwright)
