import re
from playwright.sync_api import Playwright, sync_playwright, expect


def run(playwright: Playwright) -> None:
    browser = playwright.chromium.launch(headless=False)
    context = browser.new_context()
    page = context.new_page()
    page.goto("https://erp.91miaoshou.com/?redirect=%2Fpddkj%2Fcollect_box%2Fitems")
    page.get_by_role("textbox", name="手机号/子账号/邮箱").click()
    page.get_by_role("textbox", name="手机号/子账号/邮箱").fill("lyl12345678")
    page.get_by_role("textbox", name="密码").click()
    page.get_by_role("textbox", name="密码").fill("Lyl12345678.")
    page.get_by_role("button", name="立即登录").click()
    page.get_by_role("dialog").filter(has_text="【线上直播】11月05日—11月06日线上直播预告2025").get_by_label("关闭此对话框").click()
    page.get_by_role("button", name="关闭此对话框").click()
    page.get_by_role("link", name="公用采集箱").click()
    page.get_by_role("button", name="我知道了").click()
    page.get_by_text("全部 (7687)").click()
    page.locator(".jx-checkbox__inner").first.click()
    page.locator(".jx-button.jx-button--primary.jx-button--small.is-text.pro-button.J_commonCollectBoxEdit").first.click()
    page.locator("#jx-id-6368-578").click()
    page.locator("#jx-id-6368-578").press("ControlOrMeta+a")
    page.locator("#jx-id-6368-578").fill("Lyl12345678.")
    page.locator("#jx-id-6368-578").press("ControlOrMeta+z")
    page.locator("#jx-id-6368-578").fill("")
    page.locator("#jx-id-6368-578").press("ControlOrMeta+z")
    page.locator("#jx-id-6368-578").fill("五层储物柜A092 - 可折叠带盖设计/磁性门扣/玩具书籍收纳 A0049型号")
    page.locator("#jx-id-6368-581").click()
    page.locator("#jx-id-6368-581").press("ControlOrMeta+a")
    page.locator("#jx-id-6368-581").press("ControlOrMeta+c")
    page.locator("#jx-id-6368-581").fill("产地")
    page.locator(".product-attribute-item > div:nth-child(2) > .jx-input__wrapper").first.click()
    page.locator("#jx-id-6368-582").click()
    page.locator("#jx-id-6368-582").press("ControlOrMeta+a")
    page.locator("#jx-id-6368-582").press("ControlOrMeta+c")
    page.locator("#jx-id-6368-582").fill("Guangdong,China")
    page.locator("#jx-id-6368-583").click()
    page.locator("#jx-id-6368-583").press("ControlOrMeta+a")
    page.locator("#jx-id-6368-583").press("ControlOrMeta+c")
    page.locator("#jx-id-6368-583").fill("产品推荐用途")
    page.locator("#jx-id-6368-584").click()
    page.locator("#jx-id-6368-584").press("ControlOrMeta+a")
    page.locator("#jx-id-6368-584").press("ControlOrMeta+c")
    page.locator("#jx-id-6368-584").fill("多用途")
    page.locator("#jx-id-6368-585").click()
    page.locator("#jx-id-6368-585").press("ControlOrMeta+a")
    page.locator("#jx-id-6368-585").press("ControlOrMeta+x")
    page.locator("#jx-id-6368-585").fill("形状")
    page.locator("#jx-id-6368-586").click()
    page.locator("#jx-id-6368-586").press("ControlOrMeta+a")
    page.locator("#jx-id-6368-586").press("ControlOrMeta+x")
    page.locator("#jx-id-6368-586").fill("矩形")
    page.locator("#jx-id-6368-587").click()
    page.locator("#jx-id-6368-587").press("ControlOrMeta+a")
    page.locator("#jx-id-6368-587").press("ControlOrMeta+x")
    page.locator("#jx-id-6368-587").fill("材料")
    page.locator("#jx-id-6368-588").click()
    page.locator("#jx-id-6368-588").press("ControlOrMeta+a")
    page.locator("#jx-id-6368-588").press("ControlOrMeta+x")
    page.locator("#jx-id-6368-588").fill("塑料")
    page.locator("#jx-id-6368-589").click()
    page.locator("#jx-id-6368-589").press("ControlOrMeta+a")
    page.locator("#jx-id-6368-589").press("ControlOrMeta+x")
    page.locator("#jx-id-6368-589").fill("闭合类型")
    page.locator("#jx-id-6368-590").click()
    page.locator("#jx-id-6368-590").press("ControlOrMeta+a")
    page.locator("#jx-id-6368-590").press("ControlOrMeta+x")
    page.locator("#jx-id-6368-590").fill("磁性")
    page.locator("#jx-id-6368-591").click()
    page.locator("#jx-id-6368-591").press("ControlOrMeta+a")
    page.locator("#jx-id-6368-591").press("ControlOrMeta+x")
    page.locator("#jx-id-6368-591").fill("风格")
    page.locator("#jx-id-6368-592").click()
    page.locator("#jx-id-6368-592").press("ControlOrMeta+a")
    page.locator("#jx-id-6368-592").press("ControlOrMeta+x")
    page.locator("#jx-id-6368-592").fill("现代")
    page.locator("#jx-id-6368-593").click()
    page.locator("#jx-id-6368-593").press("ControlOrMeta+a")
    page.locator("#jx-id-6368-593").press("ControlOrMeta+x")
    page.locator("#jx-id-6368-593").fill("品牌名")
    page.locator("#jx-id-6368-594").click()
    page.locator("#jx-id-6368-594").press("ControlOrMeta+a")
    page.locator("#jx-id-6368-594").press("ControlOrMeta+x")
    page.locator("#jx-id-6368-594").fill("佰森物语")
    page.locator("#jx-id-6368-595").click()
    page.locator("#jx-id-6368-595").press("ControlOrMeta+a")
    page.locator("#jx-id-6368-595").press("ControlOrMeta+x")
    page.locator("#jx-id-6368-595").fill("商品编号")
    page.locator("#jx-id-6368-596").click()
    page.locator("#jx-id-6368-596").press("ControlOrMeta+a")
    page.locator("#jx-id-6368-596").press("ControlOrMeta+x")
    page.locator("#jx-id-6368-596").fill("RC2808645")
    page.get_by_role("textbox", name="请输入规格名称").click()
    page.get_by_text("多规格").click()
    page.locator("label").filter(has_text="多规格").locator("span").nth(1).click()
    page.get_by_role("textbox", name="请输入选项名称").click()
    page.get_by_role("button", name="添加选项").click()
    page.get_by_role("group", name="* 规格一 :").locator("path").nth(1).click()
    page.locator("#jx-id-6368-628").click()
    page.locator("#jx-id-6368-628").press("ControlOrMeta+a")
    page.locator("#jx-id-6368-628").press("ControlOrMeta+x")
    page.locator("#jx-id-6368-628").fill("578.99")
    page.locator("#jx-id-6368-629").click()
    page.locator("#jx-id-6368-629").fill("99")
    page.get_by_label("规格信息: (2)").get_by_text("KG").first.click()
    page.locator("#jx-id-6368-631").click()
    page.locator("#jx-id-6368-631").fill("6000")
    page.locator("#jx-id-6368-633").click()
    page.locator("#jx-id-6368-633").fill("75")
    page.locator("#jx-id-6368-634").click()
    page.locator("#jx-id-6368-634").fill("71")
    page.locator("#jx-id-6368-635").click()
    page.locator("#jx-id-6368-635").fill("61")
    page.locator("div:nth-child(3) > .add-image-box > .add-image-box-content > .jx-icon > svg").click()
    page.get_by_text("选择空间图片").click()
    page.get_by_role("dialog", name="选择空间图片").get_by_label("关闭此对话框").click()
    page.locator("div:nth-child(3) > .add-image-box > .add-image-box-content").click()
    page.locator("#jx-id-6368-530").get_by_text("本地上传").click()
    page.locator("div:nth-child(2) > .add-image-box-content").click()
    page.locator("#jx-id-6368-627").get_by_text("本地上传").click()
    page.locator("div:nth-child(3) > .add-image-box > .add-image-box-content").click()
    page.get_by_text("使用网络图片").click()
    page.get_by_role("textbox", name="请输入图片链接，若要输入多个链接，请以回车换行").click()
    page.get_by_role("textbox", name="请输入图片链接，若要输入多个链接，请以回车换行").fill("")
    page.get_by_role("button", name="确定").click()
    page.get_by_role("dialog", name="使用网络图片").get_by_label("关闭此对话框").click()
    page.get_by_role("group", name="产品视频 :").get_by_role("img").first.click()
    page.get_by_role("group", name="产品视频 :").locator("path").nth(2).click()
    page.locator("#jx-id-6368-563").get_by_text("本地上传").click()
    page.locator("#jx-id-6368-600").click()
    page.get_by_role("textbox", name="记录供货商链接，便于采购").click()
    page.get_by_role("button", name="保存修改").click()
    page.get_by_role("group", name="* 规格一 :").get_by_role("img").nth(1).click()
    page.get_by_role("button", name="保存修改").click()
    page.locator(".jx-scrollbar__view > div:nth-child(2) > .list-goods-item > .list-goods-item-side > .goods-img-box").click()
    page.get_by_role("button", name="关闭此对话框").click()

    # ---------------------
    context.close()
    browser.close()


with sync_playwright() as playwright:
    run(playwright)
